---

- name: delete mtls policy
  oc_obj:
    state: absent
    kind: Policy
    name: "{{ istio_mtls_policy }}"
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"

- name: delete mtls destinationrule
  oc_obj:
    state: absent
    kind: DestinationRule
    name: "{{ istio_mtls_destinationrule }}"
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"

- name: delete virtualservice
  oc_obj:
    state: absent
    kind: virtualservice
    name: "{{ istio_virtualservice }}"
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"

- name: delete gateway route
  oc_obj:
    state: absent
    kind: Route
    name: "{{ istio_gateway_route }}"
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace_istio }}"