---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: '{{ tekton_pipeline_run_name }}-'
  labels:
    tekton.dev/pipeline: {{ tekton_build_publish_pipeline_name }}
spec:
  params:
    - name: gitUrl
      value: {{ assignment_rules_git_repo }}
    - name: gitRevision
      value: {{ assignment_rules_git_branch }}
    - name: workspaceDirectory
      value: source
    - name: deleteExisting
      value: 'true'
  pipelineRef:
    name: {{ tekton_build_publish_pipeline_name }}
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: {{ tekton_workspace_pvc_name }}
