---

application_name: "{{ incident_priority_service_application_name }}"

service_account: incident-priority-service

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 200m
resources_requests_memory: 200Mi

application_configmap: incident-priority-service
logging_configmap: incident-priority-service-logging

application_properties: application-config.yaml

application_image: redhat-openjdk18-openshift:1.4
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: incident-priority-service-binary-buildconfig.yml

imagestream_name: "{{ application_name }}"
imagestream_template: incident-priority-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: incident-priority-service-image-is.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: incident-priority-service-pipeline.yml

application_template: incident-priority-service.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9093
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: incident-priority

kafka_user_template: kafka-user.yml
kafka_user: incident-priority-service
kafka_user_secret: "{{ kafka_user }}"
kafka_user_truststore_type: PKCS12
kafka_user_truststore: kafka-client-truststore.p12
kafka_user_truststore_password: password
kafka_user_keystore_type: PKCS12
kafka_user_keystore: kafka-client-keystore.p12
kafka_user_keystore_password: password
kafka_user_keystore_secret: "{{ application_name }}-kafka"
kafka_user_keystore_path: /app/kafka
kafka_user_truststore_path: /app/kafka

kafka_incident_assignment_event_topic: topic-incident-event

logging_style: dev

prometheus_endpoint_path: "/metrics"
prometheus_endpoint_port: 8080