---

application_name: "{{ incident_service_application_name }}"

service_account: incident-service

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 100m
resources_requests_memory: 200Mi

application_configmap: incident-service
logging_configmap: incident-service-logging

application_properties: application.properties

application_image: redhat-openjdk18-openshift:1.4
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: incident-service-binary-buildconfig.yml

imagestream_name: "{{ application_name }}"
imagestream_template: incident-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: incident-service-image-is.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: incident-service-pipeline.yml

application_template: incident-service.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9093
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: incident-service
kafka_consumer_concurrency: 5

kafka_incident_reported_event_topic: topic-incident-event
kafka_incident_updated_event_topic: topic-incident-event
kafka_update_incident_command_topic: topic-incident-command

kafka_user_template: kafka-user.yml
kafka_user: incident-service
kafka_user_secret: "{{ kafka_user }}"
kafka_user_truststore_type: PKCS12
kafka_user_truststore: kafka-client-truststore.p12
kafka_user_truststore_password: password
kafka_user_keystore_type: PKCS12
kafka_user_keystore: kafka-client-keystore.p12
kafka_user_keystore_password: password
kafka_user_keystore_secret: "{{ application_name }}-kafka"
kafka_user_keystore_path: /app/kafka
kafka_user_truststore_path: /app/kafka

narayana_pool_max_total: 20

logging_style: dev

prometheus_endpoint_path: "/actuator/prometheus"
prometheus_endpoint_port: 8080