---

application_name: "{{ incident_service_application_name }}"

service_account: incident-service

resources_limits_cpu: 250m
resources_limits_memory: 500Mi
resources_requests_cpu: 100m
resources_requests_memory: 200Mi

application_configmap: incident-service
logging_configmap: incident-service-logging

application_properties: application.properties

application_image: redhat-openjdk18-openshift:1.4
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: incident-service-binary-buildconfig.yml

imagestream_name: "{{ application_name }}"
imagestream_template: incident-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: incident-service-image-is.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: incident-service-pipeline.yml

application_template: incident-service.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: incident-service

kafka_incident_event_topic: topic-incident-event
kafka_update_incident_command_topic: topic-incident-command
