---

application_name: "{{ incident_service_application_name }}"

service_account: incident-service

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 100m
resources_requests_memory: 200Mi

application_configmap: incident-service
logging_configmap: incident-service-logging

application_properties: application.properties

imagestream_name: "{{ application_name }}"
imagestream_template: incident-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: incident-service-image-is.yml

tekton_build_deploy_pipeline_name: build-and-deploy
tekton_pipeline_run_template: incident-service-tekton-pipeline-run.yml
tekton_pipeline_run_name: "{{ application_name }}-run"
tekton_workspace_pvc_template: incident-service-tekton-pvc.yml
tekton_workspace_pvc_name: "tekton-{{ application_name }}"
tekton_image: "image-registry.openshift-image-registry.svc:5000/{{ namespace_tools }}/{{ application_name }}:latest"

application_template: incident-service.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: incident-service
kafka_consumer_concurrency: 5

kafka_incident_reported_event_topic: topic-incident-event
kafka_incident_updated_event_topic: topic-incident-event
kafka_update_incident_command_topic: topic-incident-command

narayana_pool_max_total: 20

logging_style: dev

prometheus_endpoint_path: "/actuator/prometheus"
prometheus_endpoint_port: 8080