---

application_name: "{{ responder_simulator_service_application_name }}"

service_account: responder-simulator-service

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 200m
resources_requests_memory: 250Mi

application_configmap: responder-simulator

application_image: openjdk-11-rhel8:1.0
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: responder-simulator-service-binary-buildconfig.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: responder-simulator-service-pipeline.yml

imagestream_name: "{{ application_name }}"
imagestream_template: responder-simulator-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: responder-simulator-service-image-is.yml

application_template: responder-simulator-service.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"

kafka_mission_event_topic: topic-mission-event
kafka_mission_event_groupid: responder-simulator

kafka_responder_update_topic: topic-responder-location-update
kafka_responder_event_topic: topic-responder-event

datagrid_server_list: "{{ datagrid_application_name }}.{{ namespace_datagrid }}.svc:11222"

infinispan_cache_responder_simulator: responder-simulator
infinispan_streams_store: responder-store

