---

- name: remove scc privileged from {{ service_account }} service account
  shell: "{{ openshift_cli }} adm policy remove-scc-from-user privileged -z {{ service_account }} -n {{ namespace }}"

- name: remove scc anyuid from {{ service_account }} service account
  shell: "{{ openshift_cli }} adm policy remove-scc-from-user anyuid -z {{ service_account }} -n {{ namespace }}"

- name: delete deployment config
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete buildconfig in the {{ namespace_tools }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ buildconfig_name }}"
    namespace: "{{ namespace_tools }}"
    kind: buildconfig

- name: delete the build pipeline
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ pipeline_buildconfig_name }}"
    namespace: "{{ namespace_tools }}"
    kind: bc

- name: delete imagestream in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream

- name: delete imagestream in the {{ namespace_tools }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace_tools }}"
    kind: imagestream

- name: delete configmap
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: remove logging configmap
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ logging_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: delete service account
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"
    kind: serviceaccount

- name: delete rolebinding
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}-view"
    namespace: "{{ namespace }}"
    kind: rolebinding

