---

postgresql_service_account: postgresql
postgresql_template: "{{ resources_dir }}/postgresql.yml"
postgresql_init_configmap: "{{ postgresql_application_name }}-init"
postgresql_pv_capacity: 5Gi
postgresql_version: 9.6
postgresql_is_namespace: openshift
postgresql_max_connections: 100
postgresql_max_prepared_transactions: 100
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m

istio_mtls_destinationrule: "{{postgresql_application_name }}-client-mtls"
istio_mtls_destinationrule_template: postgresql-client-mtls-destinationrule.yml

istio_mtls_policy: "{{ postgresql_application_name }}-strict-mtls"
istio_mtls_policy_template: postgresql-mtls-policy.yml