---

- name: "copy {{ resources_base_dir }}/operatorgroup/operatorgroup.yml"
  template:
    src: "{{ resources_base_dir }}/operatorgroup/operatorgroup.yml"
    dest: "{{ work_dir }}/operatorgroup.yml"

- name: "Create operatorgroup in {{ namespace }}"
  oc_obj:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ operatorgroup_name }}"
    namespace: "{{ namespace }}"
    kind: operatorgroup
    files:
      - "{{ work_dir }}/operatorgroup.yml"