---

application_name: "{{ process_viewer_application_name }}"

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 100m
resources_requests_memory: 200Mi

application_configmap: process-viewer
logging_configmap: process-viewer-logging

service_account: process-viewer

application_properties: application-config.yaml

imagestream_name: "{{ application_name }}"
imagestream_template: process-viewer-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: process-viewer-image-is.yml

tekton_build_deploy_pipeline_name: build-and-deploy
tekton_pipeline_run_template: process-viewer-tekton-pipeline-run.yml
tekton_pipeline_run_name: "{{ application_name }}-run"
tekton_workspace_pvc_template: process-viewer-tekton-pvc.yml
tekton_workspace_pvc_name: "tekton-{{ application_name }}"
tekton_base_image: 'quay.io/btison/ubi8-java8:latest'
tekton_image: "image-registry.openshift-image-registry.svc:5000/{{ namespace_tools }}/{{ application_name }}:latest"

application_template: process-viewer.yml

logging_style: dev

process_viewer_postgresql_host: "{{ process_service_postgresql_service_name}}.{{ namespace_services }}.svc"
process_viewer_postgresql_port: 5432
process_viewer_postgresql_database: "{{ process_service_postgresql_database }}"
process_viewer_postgresql_username: "{{ process_service_postgresql_username }}"
process_viewer_postgresql_password: "{{ process_service_postgresql_password }}"