apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{ tekton_build_deploy_pipeline_name }}
spec:
  workspaces:
    - name: workspace
  params:
    - name: gitUrl
      description: git url to clone
      type: string
    - name: gitRevision
      description: git revision to checkout (branch, tag, sha, ref…)
    - name: workspaceDirectory
      description: subdirectory inside the workspace to clone the git repo into
    - name: deleteExisting
      description: clean out the contents of the workspace subdirectory (if it already exists) before cloning the repo there
    - name: buildConfig
      description: "The build config to launch"
      type: string
    - name: fromNamespace
      description: the namespace we are tagging from
      type: string
    - name: toNamespace
      description: the namespace we are tagging to
      type: string
    - name: imageStream
      description: the imagestream
      type: string
  tasks:
    - name: git-clone
      taskRef:
        name: {{ tekton_git_clone_workspace_name }}
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: subdirectory
          value: $(params.workspaceDirectory)
        - name: deleteExisting
          value: $(params.deleteExisting)
    - name: maven-build
      taskRef:
        name: {{ tekton_maven_build_task_name }}
      runAfter:
        - git-clone
      params:
        - name: buildConfig
          value: $(params.buildConfig)
      workspaces:
        - name: workspace
          workspace: workspace
    - name: ocp-build
      taskRef:
        name: {{ tekton_ocp_build_task_name }}
      runAfter:
        - maven-build
      params:
        - name: buildConfig
          value: $(params.buildConfig)
      workspaces:
        - name: workspace
          workspace: workspace
    - name: deploy
      taskRef:
        name: {{ tekton_deploy_task_name }}
      runAfter:
        - ocp-build
      params:
      - name: fromNamespace
        value: $(params.fromNamespace)
      - name: toNamespace
        value: $(params.toNamespace)
      - name: imageStream
        value: $(params.imageStream)
      - name: tag
        value: latest
