apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ tekton_deploy_task_name }}
spec:
  inputs:
    params:
      - name: fromNamespace
        description: the namespace we are tagging from
      - name: toNamespace
        description: the namespace we are tagging to
      - name: imageStream
        description: the imagestream
      - name: tag
        description: the tag
        default: latest
  steps:
    - name: tag-image
      image: {{ openshift_cli_image }}
      script: >
        oc tag
        $(inputs.params.fromNamespace)/$(inputs.params.imageStream):$(inputs.params.tag) 
        $(inputs.params.toNamespace)/$(inputs.params.imageStream):$(inputs.params.tag)
    
# TODO: commitID -> user workspaces + file?