apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ tekton_maven_build_task_name }}
spec:
  workspaces:
    - name: source
  inputs:
    params:
      - name: subdirectory
        description: subdirectory in the workspace with the application source code
        default: 'source'
      - name: artifactDirectory
        description: directory in the subdirectory with the application artifacts
        default: 'upload'
  steps:
    - name: mvn-settings
      image: {{ maven_image }}
      script: |
        #!/usr/bin/env bash
      
        DIR=$(workspaces.source.path)
        mkdir -p $DIR/.m2
        [[ -f $DIR/.m2/settings.xml ]] && \
        echo 'using existing $DIR/.m2/settings.xml' && \
        cat $DIR/.m2/settings.xml && exit 0

        cat > $DIR/.m2/settings.xml <<EOF
        <settings>
          <mirrors>
            <mirror>
              <id>mirror.default</id>
              <name>mirror.default</name>
              <url>{{ maven_mirror_url }}</url>
              <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
          <profiles>
            <profile>
              <activation>
                <activeByDefault>true</activeByDefault>
              </activation>
              <repositories>
                <repository>
                  <id>nexus-public</id>
                  <name>Nexus Public Repository</name>
                  <url>{{ maven_mirror_url }}</url>
                  <releases>
                    <enabled>true</enabled>
                  </releases>
                  <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                  </snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
        </settings>
        EOF

        [[ -f $DIR/.m2/settings.xml ]] && cat $DIR/.m2/settings.xml
        [[ -f $DIR/.m2/settings.xml ]] || echo skipping settings 

    - name: package
      image: {{ maven_image }}
      workingDir: $(workspaces.source.path)/$(inputs.params.subdirectory)
      script: >
        /usr/bin/mvn package -s $(workspaces.source.path)/.m2/settings.xml
        -Dmaven.repo.local=$(workspaces.source.path)/.m2

    - name: artifact-name
      image: {{ maven_image }}
      workingDir: $(workspaces.source.path)/$(inputs.params.subdirectory)
      script: >
        #!/usr/bin/env bash 

        set -e

        DIR=$(workspaces.source.path)
        SOURCE_DIR=$DIR/$(inputs.params.subdirectory)

        if [[ -f $SOURCE_DIR/artifact.txt ]]; then
          echo "deleting existing $SOURCE_DIR/artifact.txt"
          rm -f $SOURCE_DIR/artifact.txt
        fi

        MAVEN_ARGS="-s $(workspaces.source.path)/.m2/settings.xml
        -Dmaven.repo.local=$(workspaces.source.path)/.m2"

        echo "$(mvn help:evaluate -Dexpression=project.artifactId -q
        -DforceStdout $MAVEN_ARGS)-$(mvn help:evaluate
        -Dexpression=project.version -q -DforceStdout $MAVEN_ARGS).jar" >
        $SOURCE_DIR/artifact.txt

        echo $(cat $SOURCE_DIR/artifact.txt)

    - name: copy-artifact
      image: {{ maven_image }}
      script: >
        #!/usr/bin/env bash

        set -e

        DIR=$(workspaces.source.path)

        SOURCE_DIR=$DIR/$(inputs.params.subdirectory)
        
        ARTIFACT_DIR=$SOURCE_DIR/$(inputs.params.artifactDirectory)

        if [[ -d $ARTIFACT_DIR ]]; then
           echo "deleting existing directory $ARTIFACT_DIR"
           rm -rf $ARTIFACT_DIR
        fi

        mkdir -m 775 $ARTIFACT_DIR

        if [[ ! -f $SOURCE_DIR/artifact.txt ]]; then
           echo "file artifact.txt not found in $SOURCE_DIR - exiting"
           exit 1
        fi        

        ARTIFACT=$(cat $SOURCE_DIR/artifact.txt)

        cp $SOURCE_DIR/target/$ARTIFACT $ARTIFACT_DIR
