apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ tekton_maven_build_task_name }}
spec:
  workspaces:
    - name: workspace
  inputs:
    params:
      - name: buildConfig
        description: "The build config to launch"
  steps:
    - name: mvn-settings
      image: {{ base_image }}
      script: |
        #!/usr/bin/env bash
      
        DIR=$(workspaces.workspace.path)
        mkdir -p $DIR/.m2
        [[ -f $DIR/.m2/settings.xml ]] && \
        echo 'using existing $DIR/.m2/settings.xml' && \
        cat $DIR/.m2/settings.xml && exit 0

        cat > $DIR/.m2/settings.xml <<EOF
        <settings>
          <mirrors>
            <mirror>
              <id>mirror.default</id>
              <name>mirror.default</name>
              <url>{{ maven_mirror_url }}</url>
              <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

        [[ -f $DIR/.m2/settings.xml ]] && cat $DIR/.m2/settings.xml
        [[ -f $DIR/.m2/settings.xml ]] || echo skipping settings 

    - name: package
      image: {{ maven_image }}
      workingDir: $(workspaces.workspace.path)/source
      script: >
        /usr/bin/mvn package -s $(workspaces.workspace.path)/.m2/settings.xml
        -Dmaven.repo.local=$(workspaces.workspace.path)/.m2

    - name: artifact-name
      image: {{ maven_image }}
      workingDir: $(workspaces.workspace.path)/source
      script: >
        #!/usr/bin/env bash 

        set -e

        DIR=$(workspaces.workspace.path)

        if [[ -f $DIR/source/artifact.txt ]]; then
          echo "deleting existing $DIR/source/artifact.txt"
          rm -f $DIR/source/artifact.txt
        fi

        MAVEN_ARGS="-s $(workspaces.workspace.path)/.m2/settings.xml
        -Dmaven.repo.local=$(workspaces.workspace.path)/.m2"

        echo "$(mvn help:evaluate -Dexpression=project.artifactId -q
        -DforceStdout $MAVEN_ARGS)-$(mvn help:evaluate
        -Dexpression=project.version -q -DforceStdout $MAVEN_ARGS).jar" >
        $DIR/source/artifact.txt

        echo $(cat $DIR/source/artifact.txt)

    - name: copy-artifact
      image: {{ base_image }}
      script: >
        #!/usr/bin/env bash

        set -e

        DIR=$(workspaces.workspace.path)

        if [[ -d $DIR/source/upload ]]; then
           echo "deleting existing directory $DIR/source/upload"
           rm -rf $DIR/source/upload
        fi

        mkdir -m 775 $DIR/source/upload

        if [[ ! -f $DIR/source/artifact.txt ]]; then
           echo "file artifact.txt not found in $DIR/source - exiting"
           exit 1
        fi        

        ARTIFACT=$(cat $DIR/source/artifact.txt)

        cp $DIR/source/target/$ARTIFACT $DIR/source/upload

