apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ tekton_clone_to_workspace_task_name }}
spec:
  workspaces:
    - name: workspace
  inputs:
    resources:
      - name: source
        type: git
        targetPath: source
  steps:
    - name: copy-source-to-workspace
      image: {{ copy_source_image }}
      script: |
        #!/usr/bin/env bash

        CHECKOUT_DIR=$(workspaces.workspace.path)/source

        if [[ -d $CHECKOUT_DIR ]]; then
          echo "deleting existing directory $CHECKOUT_DIR"

          # Delete non-hidden files and directories
          rm -rf "$CHECKOUT_DIR"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "$CHECKOUT_DIR"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "$CHECKOUT_DIR"/..?*
        fi

        cp -ar $(inputs.resources.source.path)/ $(workspaces.workspace.path)/
