apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{ tekton_deploy_task_name }}
spec:
  workspaces:
    - name: source
  inputs:
    params:
      - name: fromNamespace
        description: the namespace we are tagging from
      - name: toNamespace
        description: the namespace we are tagging to
      - name: imageStream
        description: the imagestream
      - name: tag
        description: the tag
        default: latest
      - name: gitCommitId
        description: the git commit id 
        type: string

  steps:    
    - name: tag-image
      image: {{ openshift_cli_image }}
      script: >
        oc tag
        $(inputs.params.fromNamespace)/$(inputs.params.imageStream):$(inputs.params.tag) 
        $(inputs.params.fromNamespace)/$(inputs.params.imageStream):$(inputs.params.gitCommitId)
        
        oc tag
        $(inputs.params.fromNamespace)/$(inputs.params.imageStream):$(inputs.params.tag) 
        $(inputs.params.toNamespace)/$(inputs.params.imageStream):$(inputs.params.tag)

        oc tag
        $(inputs.params.fromNamespace)/$(inputs.params.imageStream):$(inputs.params.tag) 
        $(inputs.params.toNamespace)/$(inputs.params.imageStream):$(inputs.params.gitCommitId)