---

- name: "delete keycloak custom resource"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: keycloaks.keycloak.org
    name: rhsso
    namespace: "{{ namespace }}"

- name: gat all installplans in {{ namespace }} namespace
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    kind: InstallPlan
    namespace: "{{ namespace }}"
  register: r_install_plan

- name: set rhsso operator install plan name
  set_fact:
    sso_operator_install_plan_name: "{{ r_install_plan.ansible_module_results.results[0]['items'] | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'rhsso-operator')].metadata.name|[0]

- name: find all rhsso operator related csv
  set_fact:
    sso_operator_csvs: "{{ r_install_plan.ansible_module_results.results[0]['items'] | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'rhsso-operator')].spec.clusterServiceVersionNames

- name: delete all rhsso operator related csv
  when: sso_operator_csvs | length > 0
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: ClusterServiceVersion
    name: "{{ item }}"
    namespace: "{{ namespace }}"
  loop: "{{ sso_operator_csvs[0] }}"

- name: "delete subscription {{ sso_operator_subscription_name }}"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ sso_operator_subscription_name }}"
    namespace: "{{ namespace }}"
    kind: subscription

- name: remove sso operator installplan
  when:
  - sso_operator_install_plan_name is defined
  - sso_operator_install_plan_name | default("") | length > 0
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: InstallPlan
    namespace: "{{ namespace }}"
    name: "{{ sso_operator_install_plan_name }}"
  