---

- name: delete jaeger operator deployment
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: deployment
    name: {{ jaeger_operator_deployment }}
    namespace: "{{ namespace }}"

- name: delete jaeger clusterrole binding
  oc_obj:
    state: absent
    kind: ClusterRoleBinding
    name: "{{ jaeger_operator_clusterrolebinding }}"
    oc_binary: "{{ openshift_cli }}"

- name: delete jaeger operator service account
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    namespace: "{{ namespace }}"
    name: "{{ jaeger_operator_serviceaccount }}"

- name: delete jaeger operator clusterrole
  oc_obj:
    state: absent
    kind: clusterrole
    name: "{{ jaeger_operator_clusterrole }}"
    oc_binary: "{{ openshift_cli }}"
  when: uninstall_cluster_resources|bool == true

- name: delete jaeger crd
  oc_obj:
    state: absent
    kind: crd
    name: "{{ jaeger_jaegertracing_crd }}"
    oc_binary: "{{ openshift_cli }}"
  when: uninstall_cluster_resources|bool == true