---

- name: delete kiali operator deployment
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: deployment
    name: {{ kiali_operator_deployment }}
    namespace: "{{ namespace }}"

- name: delete kiali clusterrole binding
  oc_obj:
    state: absent
    kind: ClusterRoleBinding
    name: "{{ kiali_operator_clusterrolebinding }}"
    oc_binary: "{{ openshift_cli }}"

- name: delete kiali operator service account
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    namespace: "{{ namespace }}"
    name: "{{ kiali_operator_serviceaccount }}"

- name: delete kiali operator clusterrole
  oc_obj:
    state: absent
    kind: clusterrole
    name: "{{ kiali_operator_clusterrole }}"
    oc_binary: "{{ openshift_cli }}"
  when: uninstall_cluster_resources|bool == true

- name: delete kiali crd
  oc_obj:
    state: absent
    kind: crd
    name: "{{ kiali_crd }}"
    oc_binary: "{{ openshift_cli }}"
  when: uninstall_cluster_resources|bool == true