---

- name: Deploy Mapbox Simulator
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/tools.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_services }}"
        resources_dir: "{{ resources_base_dir }}/mapbox-simulator"
        work_dir_name: mapbox-simulator
    - include_role:
        name: ../roles/openshift_mapbox_simulator
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_mapbox_simulator
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"