---

- name: Deploy SSO
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/sso.yml
    - group_vars/services.yml
    - group_vars/istio.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_sso }}"
        resources_dir: "{{ resources_base_dir }}/sso"
        work_dir_name: sso
    - include_role:
        name: ../roles/openshift_sso
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_sso
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
    - include_role:
        name: ../roles/openshift_sso
        tasks_from: reset
      when: >
        ACTION is defined and
        ACTION|trim() == "reset"
