---

namespace_postgresql: "{{ project_name }}"

postgresql_init_scripts:
  - "{{ sql_scripts_git_repo }}/{{ sql_scripts_git_branch }}/emergency_response_demo_ddl.sql"

postgresql_username: naps
postgresql_password: naps
postgresql_database: emergency_response_demo

postgresql_application_name: postgresql
postgresql_credentials_secret: "{{ postgresql_application_name }}-credentials"