---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ application_name }}-git
spec:
  type: git
  params:
    - name: url
      value: {{ incident_priority_service_git_repo }}
    - name: revision
      value: {{ incident_priority_service_git_branch }}