---

- name: copy tekton pvc template
  template:
    src: "{{ resources_dir }}/{{ tekton_workspace_pvc_template }}"
    dest: "{{ work_dir }}/{{ tekton_workspace_pvc_template }}"

- name: "create the {{ tekton_workspace_pvc_name }} pvc in the {{ namespace_tools }} project"
  oc_obj:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ tekton_workspace_pvc_name }}"
    namespace: "{{ namespace_tools }}"
    kind: pvc
    files:
      - "{{ work_dir }}/{{ tekton_workspace_pvc_template }}"