---

- name: delete istio controlplane
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    namespace: "{{ namespace }}"
    name: "{{ service_mesh_controlplane_name }}"
    kind: servicemeshcontrolplane

- name: delete project
  oc_project:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ namespace }}"
  when: >
    uninstall_delete_project is defined and
    uninstall_delete_project|bool == True