---


postgresql_service_account: "{{ dw_postgresql_application_name }}"

postgresql_template: "{{ resources_dir }}/postgresql.yml"
postgresql_init_configmap: "{{ dw_postgresql_application_name }}-init"
postgresql_pv_capacity: 5Gi
postgresql_version: 9.6
postgresql_is_namespace: openshift
postgresql_max_connections: 100
postgresql_max_prepared_transactions: 100
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m

dw_postgresql_init_scripts:
  - https://raw.githubusercontent.com/Emergency-Response-Demo/sql-scripts/master/dw_database_ddl.sql

dw_postgresql_credentials_secret: "{{ dw_postgresql_application_name }}-credentials"

application_name: "{{ dw_application_name }}"
cm_name: datawarehouse
application_properties: application.properties
application_properties_resource: "{{ resources_dir }}/{{ application_properties }}"

tekton_build_deploy_pipeline_name: build-and-deploy-quarkus
tekton_pipeline_run_template: datawarehouse-tekton-pipeline-run.yml
tekton_pipeline_run_name: "{{ application_name }}-run"
tekton_workspace_pvc_template: datawarehouse-tekton-pvc.yml
tekton_workspace_pvc_name: "tekton-{{ application_name }}"
tekton_base_image: 'quay.io/btison/ubi8-java11:latest'
tekton_image: "image-registry.openshift-image-registry.svc:5000/{{ namespace_tools }}/{{ application_name }}:latest"

source_imagestream_name: "{{ application_name }}"
source_imagestream_template: datawarehouse-source-imagestream.yml

binary_imagestream_template: datawarehouse-imagestream.yml
application_template: datawarehouse-service.yml
