---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-operator
subjects:
- kind: ServiceAccount
  name: {{ kiali_operator_serviceaccount }}
  namespace: {{ namespace }}
roleRef:
  kind: ClusterRole
  name: kiali-operator
  apiGroup: rbac.authorization.k8s.io