---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: {{ istio_mtls_policy }}
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
  targets:
  - name: {{ postgresql_application_name }}