apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ postgresql_imagestream_name }}
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
    from:
      kind: DockerImage
      name: quay.io/btison/postgres-10-decoderbufs:{{ postgresql_imagestream_tag }}
    name: "{{ postgresql_imagestream_tag }}"